/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_simplejni_SimpleInterface */

#ifndef _Included_com_example_simplejni_SimpleInterface
#define _Included_com_example_simplejni_SimpleInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_simplejni_SimpleInterface
 * Method:    sayName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_simplejni_SimpleInterface_sayName
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
